// src/GraphMenu/ConfigWindow.tsx
// GraphMenu/ConfigWindow.tsx

import { useState } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { RootState } from '../redux/store';
import { setConfigs } from '../redux/slices/userInfo.slice';

interface ConfigWindowProps {
    onClose: () => void;
}

function ConfigWindow({ onClose }: ConfigWindowProps) {
    const username = useSelector((state: RootState) => state.userInfo.username);
    const llmModelFromRedux = useSelector((state: RootState) => state.userInfo.llmModel);
    const apiKeyFromRedux = useSelector((state: RootState) => state.userInfo.apiKey);

    const [llmModel, setLlmModel] = useState(llmModelFromRedux);
    const [apiKey, setAPIKey] = useState(apiKeyFromRedux);

    const dispatch = useDispatch();

    const handleSave = () => {
        dispatch(setConfigs({ llmModel: llmModel, apiKey: apiKey }));
        localStorage.setItem('llmModel', llmModel);
        localStorage.setItem('apiKey', apiKey);

        onClose();
    };

    return (
        <div className="fixed top-0 left-0 w-full h-full bg-black bg-opacity-50 flex justify-center items-center z-1000">
            <div className="bg-white p-5 rounded shadow-md w-96">
                <h2 className="text-lg font-bold mb-4 text-black">Settings</h2>
                <div className="mb-2">
                    <label className="block mb-1 text-sm text-black">
                        Username:
                        <input
                            type="text"
                            value={username}
                            readOnly
                            className="bg-gray-100 text-gray-500 cursor-not-allowed border border-gray-300 p-2 rounded w-full focus:outline-none text-black"
                        />
                    </label>
                </div>
                <div className="mb-2">
                    <label className="block mb-1 text-sm text-black">
                        LLM model:
                        <input
                            type="text"
                            value={llmModel}
                            onChange={(e) => setLlmModel(e.target.value)}
                            className="border border-gray-300 p-2 rounded w-full focus:outline-none text-black bg-white"
                        />
                    </label>
                </div>
                <div className="mb-2">
                    <label className="block mb-1 text-sm text-black">
                        API Key:
                        <input
                            type="text"
                            value={apiKey}
                            onChange={(e) => setAPIKey(e.target.value)}
                            className="border border-gray-300 p-2 rounded w-full focus:outline-none text-black bg-white"
                        />
                    </label>
                </div>
                <div className="flex justify-end mt-4">
                    <button
                        onClick={handleSave}
                        className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-2"
                    >
                        Save
                    </button>
                    <button
                        onClick={onClose}
                        className="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded"
                    >
                        Cancel
                    </button>
                </div>
            </div>
        </div>
    );
}

export default ConfigWindow;

// src/routes/graph/menu/ConfigWindow.svelte
<!-- src/routes/graph/menu/ConfigWindow.svelte -->
<script lang="ts">
	import { get } from 'svelte/store';
	import { openConfigWindow, username, llmModel, apiKey } from './menu.store';

	// Initialize local copies from the stores
	let llmModelValue = $state(get(llmModel));
	let apiKeyValue = $state(get(apiKey));

	function handleSave() {
		// Update stores
		llmModel.set(llmModelValue);
		apiKey.set(apiKeyValue);
		// Persist for next load
		localStorage.setItem('llmModel', llmModelValue);
		localStorage.setItem('apiKey', apiKeyValue);
		// Close modal
		openConfigWindow.set(false);
	}

	function handleCancel() {
		openConfigWindow.set(false);
	}
</script>

{#if $openConfigWindow}
	<div class="bg-opacity-50 fixed inset-0 z-50 flex items-center justify-center">
		<div class="w-96 rounded-lg bg-white p-6 shadow-lg">
			<h2 class="mb-4 text-xl font-semibold">Settings</h2>

			<!-- Username (read-only) -->
			<div class="mb-3">
				<label for="username" class="mb-1 block text-sm">Username:</label>
				<input
					type="text"
					id="username"
					bind:value={$username}
					readonly
					class="w-full cursor-not-allowed rounded border border-gray-300 bg-gray-100 p-2 text-gray-600"
				/>
			</div>

			<!-- LLM model -->
			<div class="mb-3">
				<label for="llmModel" class="mb-1 block text-sm">LLM model:</label>
				<input
					type="text"
					id="llmModel"
					bind:value={llmModelValue}
					class="w-full rounded border border-gray-300 p-2 focus:outline-none"
				/>
			</div>

			<!-- API Key -->
			<div class="mb-4">
				<label for="apiKey" class="mb-1 block text-sm">API key:</label>
				<input
					type="text"
					id="apiKey"
					bind:value={apiKeyValue}
					class="w-full rounded border border-gray-300 p-2 focus:outline-none"
				/>
			</div>

			<!-- Actions -->
			<div class="flex justify-end space-x-2">
				<button
					onclick={handleSave}
					class="rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700"
				>
					Save
				</button>
				<button
					onclick={handleCancel}
					class="rounded bg-gray-500 px-4 py-2 font-bold text-white hover:bg-gray-700"
				>
					Cancel
				</button>
			</div>
		</div>
	</div>
{/if}
